version: '3.8'

services:
  maildev:
    container_name: maildev
    image: maildev/maildev:2.1.0
    environment:
      - MAILDEV_INCOMING_USER=user@maildev.com
      - MAILDEV_INCOMING_PASS=user
    ports:
      - "1080:1080"
      - "1025:1025"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.3-management
    volumes:
      - "./.docker/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./.docker/rabbitmq.json:/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 10s
      retries: 6

  app:
    container_name: app
    depends_on:
      rabbitmq:
        condition: service_healthy
    image: ghcr.io/sesaquecruz/dev-challenge-app-service:release-2.2.0
    environment:
      - SERVER_PORT=8080
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - "8080:8080"

  scraper:
    container_name: scraper
    depends_on:
      rabbitmq:
        condition: service_healthy
    image: ghcr.io/sesaquecruz/dev-challenge-scraper-service:release-1.0.0
    environment:
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672
      - EMAIL_SERVER=maildev
      - EMAIL_PORT=1025
      - EMAIL_SECURE=false
      - EMAIL_USER=user@maildev.com
      - EMAIL_PASS=user
      - SCRAPER_NAVIGATION_TIMEOUT=10000
      - SCRAPER_HEADLESS=false
