name: CI Pipeline

on:
  push:
    branches:
      - main
      - hotfix/**
      - develop
      - feature/**
      - bugfix/**
  workflow_dispatch:

jobs:
  test:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
  build:
    name: Build Runner
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
